### ISSUE TITLE
License

### ISSUE THREAD

**Issue by felix-schultz** [Akiya-Research-Institute/3dGaussiansPlugin-Demo#4]
How does a commercial plugin fit the original license of gaussian splatting?

**Comment by KenjiAsaba** [comment]
- This plug-in does not use the source code from the "original" repository.
  It does not even contain CUDA or HLSL source code. It is implemented from scratch by the Unreal Engine's node-based programming.
- The user is responsible for the origin of the data created by the user. Data created in a manner forbidden for commercial use cannot be used for commercial purposes.

**Comment by felix-schultz** [comment]
So the user can not use the plugin commercially since all origin data is from software that can not be used commercially?

**Comment by KenjiAsaba** [comment]
Not "all", because some people alreay started to make open-source unofficial implementations, for example [3d-gaussian-splatting](https://github.com/WangFeng18/3d-gaussian-splatting)(MIT-license) and [taichi_3d_gaussian_splatting](https://github.com/wanmeihuali/taichi_3d_gaussian_splatting)(Apache-2.0 license). And I belive there will be more in the near future.
